### ISSUE TITLE
Exit code 73 unroted termux 

### ISSUE THREAD

**Issue by gyurmogyuri** [cargocultprog/alaterm#1]
Performing preliminary checks on your Termux system...
Downloading scripts from the alaterm repository at GitHub...
Got the scripts. Continuing...
Android may ask if you wish to stop optimizing battery usage.
You may allow or deny, but installation is faster if you allow.
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
bash: alias: =usepacman #: nem található
Pre-configuration...
Upgrading installed packages:

bash: sudo: parancs nem található
PROBLEM. Something caused preconfigure to exit early.
Exit code 73.
Script will exit now. You will be returned to Termux.

PROBLEM. Code 73. The alaterm pre-configure was interrupted.
Poor Internet connection, or server maintenance.
Wait awhile, then try again. Script resumes where it left off.
This script will now exit. Releasing Termux wakelock.

$

**Comment by cargocultprog** [comment]
Will look at this within 3 days. Cannot do it today. The problem is fixable. Please be patient. However, there is the possibility that your non-western language is mis-interpreted by my script.

**Comment by cargocultprog** [comment]
Question: When did you download the scripts from here?

**Comment by cargocultprog** [comment]
CONFIRMED and FIXED.

See file NEWS.md for instructions.
