### ISSUE TITLE
vncserver couldn't start suitable Xsession, or xinit not found

### ISSUE THREAD

**Issue by cargocultprog** [cargocultprog/alaterm#11]
NOTE TO ALL USERS: Be sure that you update Alaterm.

**Comment by TSMaitry** [comment]
$ alaterm
Starting Alaterm. Just a moment...
New localhost:1 at 127.0.0.1:5901.
View LXDE Desktop in VNC Viewer app. Password: password
To leave Alaterm and return to Termux: logout

$ pkill X
$ vncpasswd
Create an new vncserver password
$ vncserver :1
To start vncserver 
Goto vnc viewer app
127.0.0.1:5901
And your vncpasswd
Ctrl+c to logout or exit

**Comment by cargocultprog** [comment]
You misunderstood the installation. The password already was created for you. You do not need to create it in Alaterm. But you need it for the vnc server app.

**Comment by TSMaitry** [comment]
You may try this once..

**Comment by TSMaitry** [comment]
![Uploading Screenshot_2020-09-23-13-58-07-040_com.termux.jpg…]()

**Comment by TSMaitry** [comment]
![Uploading Screenshot_2020-09-23-13-58-07-040_com.termux.jpg…]()
`

**Comment by cargocultprog** [comment]
Try what once?

In any case: DO NOT issue the `vncserver` command. It will fail. Since early September 2020, Alaterm uses its own methods.
