### ISSUE TITLE
Libreoffice

### ISSUE THREAD

**Issue by dk009dk** [cargocultprog/alaterm#3]
Libreoffice isn't working

On terminal it shows this error

ERROR: /proc not mounted - LibreOffice is unlikely to work well if at all

**Comment by cargocultprog** [comment]
I cannot help you, unless you provide information. What is your device? Which version of Android? Is it rooted, or using Dex? Did you get Termux from Google Play or F-Droid?

LibreOffice works for me. A new re-install also works. I am using libreoffice-fresh.

**Comment by dk009dk** [comment]
> I cannot help you, unless you provide information. What is your device? Which version of Android? Is it rooted, or using Dex? Did you get Termux from Google Play or F-Droid?
> 
> LibreOffice works for me. A new re-install also works. I am using libreoffice-fresh.

Device Redmi note 7
Android 9
Non-rooted
Termux from play store

**Comment by cargocultprog** [comment]
Then LibreOffice should work, unless your product has a security feature that blocks something.

I know an alternative method that is likely to solve the problem. Come back tomorrow. That will give me time to test it.

**Comment by cargocultprog** [comment]
This is a well-known issue with LibreOffice on Linux, and is not specific to alaterm. My installaion scripts automatically fix it. However, other machines may not be able to use that fix. It may depend on how much security software you use.

So, there is another fix, thanks to GitHub user Zin-Uru. I just uploaded a file `fixlo` to the project page. Download it, and run it in Termux, but **not** within alaterm:

```
bash fixlo
```

Then try to launch LibreOffice. Tell me what happens.

If it works, then you will have to re-run `fixlo` after each time that you update LibreOffice software.

**Comment by dk009dk** [comment]
> This is a well-known issue with LibreOffice on Linux, and is not specific to alaterm. My installaion scripts automatically fix it. However, other machines may not be able to use that fix. It may depend on how much security software you use.
> 
> So, there is another fix, thanks to GitHub user Zin-Uru. I just uploaded a file `fixlo.bash` to the project page. Download it, and run it in Termux, but **not** within alaterm:
> 
> ```
> bash fixlo.bash
> ```
> 
> Then try to launch LibreOffice. Tell me what happens.
> 
> If it works, then I can modify the other alaterm installer scripts to make the fix automatic.

**Comment by dk009dk** [comment]
Now it's working properly without running fixlo.bash 


Thank you.
