### ISSUE TITLE
Advice for you to add sound support

### ISSUE THREAD

**Issue by JanuszChmiel** [cargocultprog/alaterm#8]
It is easy to add sound support. and it is not dangerous or complex. Because I do not see at all, I AM successfully using sound support by using Pulseaudio for Termux and many Linux distros including Ubuntu, Debian, ArchLinux. The only one magic is to include command to install pulseaudio sox from The Termux perspective.

Then it is necessary to install PUlseaudio also on The Arch Linux
pacman -S pulseaudio
Really, it will work. But you must add The following lines to The initialisation script which executes ArchLinux.

pulseaudio --start --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
Then add The following line to /etc/profile which will The part of Target ArchLinux with Lxde distribution.

export PULSE_SERVER=127.0.0.1

Sure, it will be better to add Pulseaudio initialisation line also to The /profile script for Termux.
What is possible? Many sound operations except recording from sound input devices.

You would even made A big joy to mane visually impaired users when you would find which Gconf key lxappearance changes when sighted Lxde user will check The checkbox enable assistive technology support.
Then if you would try to add some Script command which would add this Gconf key visually impaired users could simply install orca
pacman -S orca
And Lxde could work with Ora screen reader.
Orca work perfectly for Mate for Now. but Lxde uses less RAm and less CPU cycles what is very important.
And Lxde do not communicate with system bus so less system errors on Terminal output while comparing with Mate-session, which communicate with system bus which can be only accessed if real Linux kernel is available.
It do not crash Mate, but it creates some error potential.
Thank you very much for yours understanding and for yours time.

**Comment by cargocultprog** [comment]
Agreed. I had Audacious running, using a similar method. But I thought the configuration was too complex, because it is possible to run an ordinary Android music app in the background.

Video is too slow. Better to let Android do it.

A few audio programs are unable to connect with PulseAudio. They insist on Jack, or Alsa-oss.

I will mention your solution in the next Help update.
